name: selenium-windows-tests

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      Solution_Name: TrelloTestFramework/TrelloTestFramework.sln  # Corrected path to the solution file
      Test_Project_Path: TrelloTestFramework/TrelloTestFramework/TrelloTestFramework.csproj  # Corrected path to the project file

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Release

    - name: Run tests
      run: dotnet test ${{ env.Test_Project_Path }} --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: test_results.trx
